name: Test

on:
  workflow_call:
  pull_request:

jobs:
  test-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm install -g truffle

      - name: Test
        run: npm run contracts:test